language: node_js
sudo: required
node_js:
  - "7"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.elm
before_install:
  - uname -a # print the *exact* operating system/kernel version
  - | # build time improvement see: https://git.io/vQcqz
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
install:
  - npm i create-elm-app -g

jobs:
  include:
    - stage: "Test"
      script: elm-app test

    - stage: "Build"
      script: elm-app build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        target-branch: gh-pages
        local-dir: ./build
        on:
          branch: master
